[font]
normal.family = "Syne Mono"
bold.family = "Syne Mono"
italic.family = "Syne Mono"
size = 11.0

[general]
import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
