[General]
type=image
background=/usr/share/backgrounds/wallpaper.jpg
backgroundMode=fill
blur=true
recursiveBlurLoops=2
recursiveBlurRadius=7

[Design]
MainColor=#c6d0f5
AccentColor=#80c8ff
BackgroundColor=#303446
OverlayColor=#232634CC
Font=AudioLink Mono
FontSize=

[UsersList]
enableAvatars=false
userFont=AudioLink Mono
userFontSize=18
userColor=#babbf1
